branches:
  only:
    - master
    - develop

skip_tags: true

image:
  - Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_API_KEY:
    secure: PgpXSB0GvAv4h6AD4klpEgaXpXNI/PD9ww5kegq3PMgDjvXYFF0O/xWUYATyA1EO
  COVERALLS_REPO_TOKEN:
    secure: DHCaoxVunFrlGvtXJRcYaw432X5AY5GcYIVI6C1xsr1Tskj7uM/dJapC/R6S7wub

install:
  - dotnet tool install --global Ubiety.VersionIt

build_script:
  - ps: .\build.ps1 --bootstrap
  - ps: .\build.ps1 --currentBranch=$env:APPVEYOR_REPO_BRANCH --nugetKey=$env:NUGET_API_KEY --coverallsToken=$env:COVERALLS_REPO_TOKEN --verbosity=diagnostic

test: off
deploy: off
